function connectivity = getConnectivity(X,Y,Z)

[Ny,Nx] = size(X);

if nargin == 3
    dist1 = sqrt( ...
        (X(1:Ny-1,1:Nx-1) - X(2:Ny,2:Nx)).^2 + ...
        (Y(1:Ny-1,1:Nx-1) - Y(2:Ny,2:Nx)).^2 + ...
        (Z(1:Ny-1,1:Nx-1) - Z(2:Ny,2:Nx)).^2 ...
        );
    dist2 = sqrt( ...
        (X(1:Ny-1,2:Nx) - X(2:Ny,1:Nx-1)).^2 + ...
        (Y(1:Ny-1,2:Nx) - Y(2:Ny,1:Nx-1)).^2 + ...
        (Z(1:Ny-1,2:Nx) - Z(2:Ny,1:Nx-1)).^2 ...
        );
elseif nargin == 2
    dist1 = sqrt( ...
        (X(1:Ny-1,1:Nx-1) - X(2:Ny,2:Nx)).^2 + ...
        (Y(1:Ny-1,1:Nx-1) - Y(2:Ny,2:Nx)).^2 ...
        );
    dist2 = sqrt( ...
        (X(1:Ny-1,2:Nx) - X(2:Ny,1:Nx-1)).^2 + ...
        (Y(1:Ny-1,2:Nx) - Y(2:Ny,1:Nx-1)).^2 ...
        );
end

connectivity = [];

for ix = 1:Nx-1
    for iy = 1:Ny-1
        if dist1(iy,ix) <= dist2(iy,ix)
            connectivity = [connectivity; ...
                [(ix-1)*Ny+iy, ix*Ny+iy, ix*Ny+iy+1];...
                [(ix-1)*Ny+iy, ix*Ny+iy+1, (ix-1)*Ny+iy+1]];
        else
            connectivity = [connectivity; ...
                [(ix-1)*Ny+iy, ix*Ny+iy, (ix-1)*Ny+iy+1];...
                [ix*Ny+iy, ix*Ny+iy+1, (ix-1)*Ny+iy+1]];
        end
    end
end

end