function [Lx,Ly] = sideLength(dataX,dataY,dataZ)
% Side length of surface
Lx = sum(sqrt((dataX(1,2:end)-dataX(1,1:end-1)).^2 ...
    + (dataY(1,2:end)-dataY(1,1:end-1)).^2 ...
    + (dataZ(1,2:end)-dataZ(1,1:end-1)).^2));
Ly = sum(sqrt((dataX(2:end,1)-dataX(1:end-1,1)).^2 ...
    + (dataY(2:end,1)-dataY(1:end-1,1)).^2 ...
    + (dataZ(2:end,1)-dataZ(1:end-1,1)).^2));
end